USERNAME ?= $(shell bash -c 'read -p "Please enter your username.  To avoid entering this each time please update USERNAME field in the Makefile.credentials file in the directory root to your username.  " pwd; echo $$pwd')

deploy-prod:
	fab2 -H ${USERNAME}@ucr-gnps2 \
	deploy-workflow ".."

deploy-beta:
	fab2 -H ${USERNAME}@ucr-gnps2-beta \
	deploy-workflow ".."
